name = "SPICE"
uuid = "3eddf760-1f36-11e9-3d75-2330dfea9323"
authors = ["Nathan Parrish <parrish@advanced-space.com>"]
version = "0.1.0"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RemoteFiles = "cbe49d4c-5af1-5b60-bb70-0a60aa018e1b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
